### ISSUE TITLE
Database not automatically created (no documentation?)

### ISSUE THREAD

**Issue by fragtion** [afterlogic/aurora-files#10]
Hi.  I've installed aurora-files from GIT master repo. Installation was quite straightforward until I opened my browser to the installation directory and tried to log in with superadmin. I received the following error:

The username or password you entered is incorrect. (Not enough details required to establish connection.)

Turns out this is a DB connect issue. So I changed DBName, DBLogin, and DBPassword details for MySQL server in 'data/settings/config.json'. Then it told me that the DBName does not exist.

Database configuration is not explained in the README for Installation.  I followed all steps, and am running as follows:

root@server:/usr/local/src/aurora-files# gulp js:min
[16:15:23] Using gulpfile /usr/local/src/aurora-files/gulpfile.js
[16:15:23] Starting 'js:min'...
[16:15:24] Finished 'js:min' after 244 ms
[16:15:49] Time: 24523ms

What could I be missing?

Thank you.

**Comment by afterlogic-support** [comment]
Main documentation on the product can be found at: https://afterlogic.com/docs/aurora-files
And whether you're installing [from package](https://afterlogic.com/docs/aurora-files/installation/installing-from-package) or [from repository](https://afterlogic.com/docs/aurora-files/installation/installing-from-repository), the instructions explicitly state: Upon installing the product, you'll need to [configure your installation](https://afterlogic.com/docs/aurora-files/configuration) - and configuring the database settings is mentioned there too.

Hope that clears up the confusion. Thank you.

**Comment by fragtion** [comment]
Hi,

The problem is that on first logon as "superadmin", it gave this error. So there was no opportunity to configure the DB.  Problem is not resolved for me. Plse advise?

**Comment by afterlogic-support** [comment]
Oh, I might have misunderstood the original inquiry. But can you please check if the issue occurs if you install the product from a package, too? Installing from GitHub is mostly a developer case which may be unstable, not something intended for production use.

**Comment by fragtion** [comment]
Great Idea I will try to install from package and provide feedback from there. Thanks

**Comment by afterlogic-support** [comment]
Developers have confirmed there was indeed a bug in the repository, and it's fixed now. As for the package, it apparently was released earlier and was not affected by the issue.

**Comment by fragtion** [comment]
Hi @afterlogic-support 

Please could you ask your developers to push the bugfix to master repo?  There have been no commits for 17 days, but it was 5 days ago that I pulled from master (8c39373) and ran into this issue on that revision.

As soon as a commit is made , I will try to install from git/dev again and report if any issues persist

Many thanks

**Comment by afterlogic-support** [comment]
That's not currently possible due to rather intense development going on, we'll have the tags updated on the next release approximately expected in a couple weeks.

**Comment by fragtion** [comment]
Ok, Thanks for feedback. I will wait.

Also, that means this is still an ongoing issue.  I recommend re-opening it accordingly so other users can see :)

Take care

**Comment by afterlogic-support** [comment]
The thread is closed due to inactivity. Should the issue persist, please feel free to reopen and provide an update. Thank you.
